name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Docker Registry Login
      run: echo ${{ secrets.ACR_SECRET }} | docker login myacrschoewe.azurecr.io --username 1a2115d1-c6e5-415c-ae7a-42a5675adcd5 --password-stdin
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
